version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recommendation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data:
